#! /usr/bin/python
# -*- coding: utf8 -*-

from collections import OrderedDict
import common_definition as CMN_DEF


SCRAPY_MODULE_FOLDER = "scrapy"

SCRAPY_METHOD_TYPE_SELENIUM_STOCK = {"need_selenium": True, "need_company_number": True,}
SCRAPY_METHOD_TYPE_SELENIUM_MARKET = {"need_selenium": True, "need_company_number": False,}
SCRAPY_METHOD_TYPE_REQUESTS_STOCK = {"need_selenium": False, "need_company_number": True,}
SCRAPY_METHOD_TYPE_REQUESTS_MARKET = {"need_selenium": False, "need_company_number": False,}

SCRAPY_METHOD_CONSTANT_CFG = OrderedDict()

# Market Start
SCRAPY_METHOD_OPTION_PUT_CALL_RATIO_NAME = "option put call ratio"
SCRAPY_METHOD_OPTION_PUT_CALL_RATIO_CFG = {# 臺指選擇權賣權買權比
    "description": u'臺指選擇權賣權買權比',
    "module_name": "taifex_scrapy",
    "class_name": "TaifexScrapy",
    "url_time_unit": CMN_DEF.DATA_TIME_UNIT_MONTH,
}
SCRAPY_METHOD_OPTION_PUT_CALL_RATIO_CFG.update(SCRAPY_METHOD_TYPE_REQUESTS_MARKET)
SCRAPY_METHOD_CONSTANT_CFG[SCRAPY_METHOD_OPTION_PUT_CALL_RATIO_NAME] = SCRAPY_METHOD_OPTION_PUT_CALL_RATIO_CFG

SCRAPY_METHOD_TFE_OPEN_INTEREST_NAME = "TFE open interest"
SCRAPY_METHOD_TFE_OPEN_INTEREST_CFG = {
    "description": u'台指期未平倉(大額近月、法人所有月)',
    "module_name": "wearn_scrapy",
    "class_name": "WEarnWebScrapy",
    "url_time_unit": CMN_DEF.DATA_TIME_UNIT_DAY,
}
SCRAPY_METHOD_TFE_OPEN_INTEREST_CFG.update(SCRAPY_METHOD_TYPE_SELENIUM_MARKET)
SCRAPY_METHOD_CONSTANT_CFG[SCRAPY_METHOD_TFE_OPEN_INTEREST_NAME] = SCRAPY_METHOD_TFE_OPEN_INTEREST_CFG
# Market End

# Stock Start
SCRAPY_METHOD_REVENUE_NAME = "revenue"
SCRAPY_METHOD_REVENUE_CFG = {# 營收盈餘
    "description": u'營收盈餘',
    "module_name": "cmoney_scrapy",
    "class_name": "CMoneyWebScrapy",
    "url_time_unit": CMN_DEF.DATA_TIME_UNIT_MONTH,
}
SCRAPY_METHOD_REVENUE_CFG.update(SCRAPY_METHOD_TYPE_SELENIUM_STOCK)
SCRAPY_METHOD_CONSTANT_CFG[SCRAPY_METHOD_REVENUE_NAME] = SCRAPY_METHOD_REVENUE_CFG

SCRAPY_METHOD_PROFITABILITY_NAME = "profitability"
SCRAPY_METHOD_PROFITABILITY_CFG = {# 獲利能力
    "description": u'獲利能力',
    "module_name": "cmoney_scrapy",
    "class_name": "CMoneyWebScrapy",
    "url_time_unit": CMN_DEF.DATA_TIME_UNIT_QUARTER,
}
SCRAPY_METHOD_PROFITABILITY_CFG.update(SCRAPY_METHOD_TYPE_SELENIUM_STOCK)
SCRAPY_METHOD_CONSTANT_CFG[SCRAPY_METHOD_PROFITABILITY_NAME] = SCRAPY_METHOD_PROFITABILITY_CFG

SCRAPY_METHOD_CASHFLOW_STATEMENT_NAME = "cashflow statement"
SCRAPY_METHOD_CASHFLOW_STATEMENT_CFG = {# 現金流量表
    "description": u'現金流量表',
    "module_name": "cmoney_scrapy",
    "class_name": "CMoneyWebScrapy",
    "url_time_unit": CMN_DEF.DATA_TIME_UNIT_QUARTER,
}
SCRAPY_METHOD_CASHFLOW_STATEMENT_CFG.update(SCRAPY_METHOD_TYPE_SELENIUM_STOCK)
SCRAPY_METHOD_CONSTANT_CFG[SCRAPY_METHOD_CASHFLOW_STATEMENT_NAME] = SCRAPY_METHOD_CASHFLOW_STATEMENT_CFG

SCRAPY_METHOD_DIVIDEND_NAME = "dividend"
SCRAPY_METHOD_DIVIDEND_CFG = {# 股利政策
    "description": u'股利政策',
    "module_name": "cmoney_scrapy",
    "class_name": "CMoneyWebScrapy",
    "url_time_unit": CMN_DEF.DATA_TIME_UNIT_YEAR,
}
SCRAPY_METHOD_DIVIDEND_CFG.update(SCRAPY_METHOD_TYPE_SELENIUM_STOCK)
SCRAPY_METHOD_CONSTANT_CFG[SCRAPY_METHOD_DIVIDEND_NAME] = SCRAPY_METHOD_DIVIDEND_CFG

SCRAPY_METHOD_INSTITUTIONAL_INVESTOR_NET_BUY_SELL_NAME = "institutional investor net buy sell"
SCRAPY_METHOD_INSTITUTIONAL_INVESTOR_NET_BUY_SELL_CFG = {# 三大法人買賣超
    "description": u'三大法人買賣超',
    "module_name": "goodinfo_scrapy",
    "class_name": "GoodInfoWebScrapy",
    "url_time_unit": CMN_DEF.DATA_TIME_UNIT_DAY,
}
SCRAPY_METHOD_INSTITUTIONAL_INVESTOR_NET_BUY_SELL_CFG.update(SCRAPY_METHOD_TYPE_SELENIUM_STOCK)
SCRAPY_METHOD_CONSTANT_CFG[SCRAPY_METHOD_INSTITUTIONAL_INVESTOR_NET_BUY_SELL_NAME] = SCRAPY_METHOD_INSTITUTIONAL_INVESTOR_NET_BUY_SELL_CFG
# Stock End

SCRAPY_METHOD_NAME = SCRAPY_METHOD_CONSTANT_CFG.keys()
SCRAPY_METHOD_LEN = len(SCRAPY_METHOD_NAME)
SCRAPY_METHOD_NAME_TO_INDEX = {name: index for index, name in enumerate(SCRAPY_METHOD_NAME)}
SCRAPY_METHOD_DESCRIPTION = [cfg["description"] for cfg in SCRAPY_METHOD_CONSTANT_CFG.values()]
SCRAPY_METHOD_URL_TIME_UNIT = [cfg['url_time_unit'] for cfg in SCRAPY_METHOD_CONSTANT_CFG.values()]
SCRAPY_METHOD_MODULE_NAME = [cfg["module_name"] for cfg in SCRAPY_METHOD_CONSTANT_CFG.values()]
SCRAPY_METHOD_CLASS_NAME = [cfg["class_name"] for cfg in SCRAPY_METHOD_CONSTANT_CFG.values()]
SCRAPY_CSV_FILENAME = [method_name.replace(" ", "_").lower() for method_name in SCRAPY_METHOD_NAME]

SCRAPY_METHOD_OPTION_PUT_CALL_RATIO_INDEX = SCRAPY_METHOD_NAME.index(SCRAPY_METHOD_OPTION_PUT_CALL_RATIO_NAME)
SCRAPY_METHOD_TFE_OPEN_INTEREST_INDEX = SCRAPY_METHOD_NAME.index(SCRAPY_METHOD_TFE_OPEN_INTEREST_NAME)
SCRAPY_METHOD_REVENUE_INDEX = SCRAPY_METHOD_NAME.index(SCRAPY_METHOD_REVENUE_NAME)
SCRAPY_METHOD_PROFITABILITY_INDEX = SCRAPY_METHOD_NAME.index(SCRAPY_METHOD_PROFITABILITY_NAME)
SCRAPY_METHOD_CASHFLOW_STATEMENT_INDEX = SCRAPY_METHOD_NAME.index(SCRAPY_METHOD_CASHFLOW_STATEMENT_NAME)
SCRAPY_METHOD_DIVIDEND_INDEX = SCRAPY_METHOD_NAME.index(SCRAPY_METHOD_DIVIDEND_NAME)
SCRAPY_METHOD_INSTITUTIONAL_INVESTOR_NET_BUY_SELL_INDEX = SCRAPY_METHOD_NAME.index(SCRAPY_METHOD_INSTITUTIONAL_INVESTOR_NET_BUY_SELL_NAME)

SCRAPY_METHOD_START = 0
SCRAPY_METHOD_END = len(SCRAPY_METHOD_NAME)