#! /usr/bin/python
# -*- coding: utf8 -*-

CMONEY_TABLE0_DIVIDEND_MAX_DATA_COUNT = 8
CMONEY_TABLE1_MAX_DATA_COUNT = 8
CMONEY_TABLE_DEF_DATA_COUNT = 1
CMONEY_STOCK_TABLE_DEF_TIME_UNIT = 0

STATEMENT_DOG_SHEET_INTERVAL_LAST_3_YEARS = 0
STATEMENT_DOG_SHEET_INTERVAL_LAST_5_YEARS = 1
STATEMENT_DOG_SHEET_INTERVAL_LAST_8_YEARS = 2
STATEMENT_DOG_SHEET_INTERVAL_SELF_DEFINE = 3